version: 2

project_name: relax

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"